language: python
python:
  - '2.7'
  - '3.4'
sudo: false
os:
  - linux
install:
  - pip install --upgrade pip
  - pip install flake8
  - pip install coveralls
before_script:
  - flake8 --show-source --max-line-length=80 --statistics --builtins=_ rainmachine
script:
  - python setup.py install
  - python setup.py sdist
  - rainmachine --help
  - rainmachine --version
after_success:
  - coveralls
deploy:
  - provider: pypi
    user: $pypi_test_user
    password: $pypi_test_pass
    server: $pypi_test
    on:
      branch: deploy-test
      python: '3.4'
  - provider: pypi
    user: $pypi_user
    password: $pypi_pass
    server: $pypi
    on:
      branch: deploy
      python: '3.4'
